FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* ./
RUN npm install
COPY . .
# RUN npm run dev
# RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]
